### ISSUE TITLE
projects

### ISSUE THREAD

**Issue by grammaton** [collegiata/docs#1]
il nome `projects` oltre ad essere di dubbio gusto duplica il pannello `Projects` dell'interfaccia di GitHub.

proposte per questo repo

 - [ ] tex
 - [x] docs
 - [ ] papers

**Comment by grammaton** [comment]
@nenelenen @demartinomrc proponete, votate e chiudete se necessario

**Comment by demartinomrc** [comment]
docs

**Comment by nenelenen** [comment]
anche io voto docs! speravo bastasse mettere il tick :/

**Comment by nenelenen** [comment]
Non so come si modifica. Va fatta nuova?

**Comment by grammaton** [comment]
Il baffo è uno voi siete due. 
Vada per doc. Si fa dai Settings la posso rinominare io quando arrivo a roma

**Comment by grammaton** [comment]
Brava @nenelenen
